# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Netflix-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Netflix-clone
  
  # SnapKit
  pod 'SnapKit', '~> 5.6.0'
  
  # RxSwift
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  
  # Alamofire
  pod 'Alamofire'

end
